# DYCD Programs and Demography

# Background

Research question: Are DYCD program sites correlated with demographic characteristics?
DYCD: New York City Department of Youth and Community Development

Variables
- Number DYCD 2019 program sites per zip code
- 2019 NY Demographic statistics per zip code

Goals
- Compute correlations between demographic characteristics and number of DYCD 2019 program sites per zip code
  Demographic characteristics: population count, gender, ethnicity, US citizens, public assistance
- Create data visualisation of the results

## Libraries

In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## Source data

In [28]:
demostats = pd.read_csv("Demographicstats.csv")
demostats

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,10001,44,22,0.50,22,0.50,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
1,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
2,10003,1,1,1.00,0,0.00,0,0,1,100,...,1,100,0,0.00,1,1.00,0,0,1,100
3,10004,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,10005,2,2,1.00,0,0.00,0,0,2,100,...,2,100,0,0.00,2,1.00,0,0,2,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,12788,83,39,0.47,44,0.53,0,0,83,100,...,83,100,35,0.42,48,0.58,0,0,83,100
232,12789,272,115,0.42,157,0.58,0,0,272,100,...,272,100,70,0.26,202,0.74,0,0,272,100
233,13731,17,2,0.12,15,0.88,0,0,17,100,...,17,100,7,0.41,10,0.59,0,0,17,100
234,16091,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
235,20459,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0

In [27]:
progsites = pd.read_csv("Programsites.csv")
progsites

,Date,Service Category,Program Area,Program Type,Provider,Program Site Name,Borough,Street Address,City,State,...,NDA,NTA,BIN,BBL,Location,Zip Codes,Community Districts,Borough Boundaries,City Council Districts,Police Precincts
0,06/01/2019,Afterschool Programs,Compass,COMPASS Elementary,"Imani House, Inc.",P.S. 282 Park Slope,Brooklyn,180 6 AVENUE,BROOKLYN,NY,...,NaN,NaN,3019597.0,3.009500e+09,POINT (-73.97774 40.67672),17619.0,14.0,2.0,27.0,50.0
1,06/01/2019,Afterschool Programs,Compass,COMPASS Elementary,Coalition for Hispanic Family Services,P.S. 123 Suydam,Brooklyn,100 IRVING AVENUE,BROOKLYN,NY,...,NaN,BK77,3072966.0,3.032100e+09,POINT (-73.9227 40.70377),13828.0,42.0,2.0,30.0,53.0
2,06/01/2019,Afterschool Programs,Beacon,Beacon,"Queens Community House, Inc.",30Q149 - P.S. 149 Christa Mcauliffe School,Queens,93-11 34th Avenue,Jackson Heights,NY,...,Queens Neighborhood Development Area 003,QN28,4035441.0,4.014410e+09,POINT (-73.87461 40.75484),14783.0,65.0,3.0,5.0,73.0
3,06/01/2019,Afterschool Programs,Compass,COMPASS Elementary,Brooklyn Childrens Museum Corp,P.S. 189 The Bilingual Center,Brooklyn,1100 EAST NEW YORK AVENUE,BROOKLYN,NY,...,NaN,BK81,3099537.0,3.045990e+09,POINT (-73.92625 40.665560000000006),17614.0,61.0,2.0,17.0,40.0
4,06/01/2019,Community Services,Compass,COMPASS Elementary,HANAC INC,P.S. 212 -Q-,Queens,34-25 82 STREET,QUEENS,NY,...,NaN,QN28,4437128.0,4.014430e+09,POINT (-73.88491 40.75308),14783.0,65.0,3.0,5.0,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6024,06/01/2019,Immigrant Services,CSBG,Seniors,Conscientious Musical Revues,Grace Agaard Senior CEnter,Brooklyn,966 Fulton St.,Bklyn,NY,...,Brooklyn Neighborhood Development Area 002,BK69,3057638.0,3.020140e+09,POINT (-73.96218 40.68249),13829.0,68.0,2.0,48.0,55.0
6025,06/01/2019,Jobs and Internships,SYEP,NYCHA MAP,"United Activities Unlimited, Inc.",UAU Bay ST,Staten Island,15 William Street,Staten Island,NY,...,1,SI37,5013400.0,5.005080e+09,POINT (-74.07705 40.63095),10691.0,4.0,1.0,13.0,74.0
6026,06/01/2019,Immigrant Services,CSBG,Seniors,Neighborhood Self-Help by Older Persons Projec...,Highbridge Gardens,Bronx,1145 University Avenue,Bronx,NY,...,Bronx Neighborhood Development Area 004,BX26,2095219.0,2.025270e+09,POINT (-73.92828 40.83708000000001),10930.0,50.0,5.0,42.0,27.0
6027,06/01/2019,Immigrant Services,CSBG,NDA Healthy Families,Bedford Stuyvesant Restoration Corp,Jobs-Plus,Brooklyn,630 Flushing Avenue,brooklyn,NY,...,Brooklyn Neighborhood Development Area 003,BK75,3329628.0,3.017200e+09,POINT (-73.94845 40.699960000000004),17213.0,69.0,2.0,49.0,51.0
6028,06/01/2019,Jobs and Internships,SYEP,Older Youth (OY),ST. NICKS ALLIANCE CORP.,St. Nicks Alliance at Grand Street Campus,Brooklyn,850 Grand Street,Brooklyn,NY,...,NaN,BK78,3325733.0,3.030160e+09,POINT (-73.93972 40.71218),17613.0,36.0,2.0,30.0,56.0