# 4. Citybenches: Implementation

In [7]:
#Necessary packages
import osmnx as ox
import networkx as nx
import geopandas 
import matplotlib.pyplot as plt
import pandas as pd

## Results of Data Wrangling Round 1

In [9]:
#Import data frame, adding 'New York City' to every field in Address-column
df = pd.read_excel('citybenchlocationsv03.xlsx')
df['Address'] = df['Address'] + ', New York City'

In [10]:
#Subset original data set
addressborough = df[['Address', 'Borough']]

In [11]:
#Further subsetting
addressm = addressborough.loc[addressborough['Borough'] == 'Manhattan']

## 4.1 Data Wrangling: Round 2

First we have to add a column with geocodes to the data frame. We have chosen a try-and-except-loop so that the loop will not be interrupted in case there are addresses that cannot be geocoded. If an address cannot be geocoded, the field in the geocode-column is filled by a whitespace.

In [ ]:
#Adding a column with geocodes to df
addressgeo = []
for i in addressm['Address']:
    try:
        addressgeo.append(ox.geocode(i))
    except:
        addressgeo.append(' ')
        pass
addressm.insert(2, 'Geocode', addressgeo, True)

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>

Because the geocoding process needs a lot of time, we saved it as a .pkl so we need not to repeat this process every time we launch the jupyter notebook.

In [8]:
addressm = pd.read_pickle("addressm.pkl")

In [11]:
addressm.head()

,Address,Borough,Geocode,Node
0,"540 West 145th Street, New York City",Manhattan,"(40.8260052, -73.949854)",561035361
56,"145 & 147 Madison Ave, New York City",Manhattan,"(40.74619633333333, -73.983977)",3252586222
57,"165 Madison Avenue, New York City",Manhattan,"(40.746812750000004, -73.98327882871746)",42445903
58,"191 Madison Avenue, New York City",Manhattan,"(40.74802628571428, -73.98264385714285)",4960503208
59,"199 Madison Avenue, New York City",Manhattan,"(40.7482878, -73.9824103)",4960503208

In [9]:
#data = addressm.to_pickle("addressm.pkl")

Now we check all the fields in the geocode-column that are filled with whitespaces. The addresses that belong to these fields are the addresses that cannot be geocoded by ox.geocode(), so we need to find their geocode manually using the google maps user interface.

In [10]:
#Checking Geocoder
fgeocode = []
for i in range(len(addressm)):
    if addressm.iloc[i]['Geocode'] == ' ':
        fgeocode.append(addressm.index[i])       
print(fgeocode)

[]

In [14]:
# Buggy addresses
for i in fgeocode:
    print(addressm.loc[i]['Address'])

Lexington Avenue & East 118th Street, New York City
240 First Avenue, New York City
125 East 116thStreet, New York City
421-435 East 116th Street, New York City
421-435 East 116th Street, New York City
617 Second Avenue, New York City
East Houston and Bowery, New York City
West 36th Street between 9th Avenue &
Dyer Avenue, New York City
West 36th Street between 9th Avenue &
Dyer Avenue, New York City
York Avenue between E70th & E71st
Street, New York City
York Avenue between E70th & E71st
Street, New York City
2nd Avenue between E90th & E91st
Street, New York City
250 W65th Street, New York City
518 West 125 Street, New York City
2611 Frederick Douglas Boulevard, New York City
Varick Street between Watts Street &
Broome Street, New York City
Varick Street between Watts Street &
Broome Street, New York City
Hudson Street between Canal Street &
Broome Street, New York City
Hudson Street between Canal Street &
Broome Street, New York City
Division Street between Market &
Forsyth Street, New York City
Division Street between Market &
Forsyth Street, New York City
2541 Adam Clayton Powell Boulevard, New York City
20 Lincoln Center Plaza, New York City
Holcombe Rucker Park, New York City
W 155th Street & Edgecombe Avenue, New York City
Manhattan Bridge approach, New York City
Manhattan Bridge approach, New York City
Manhattan Bridge approach, New York City
Manhattan Bridge approach, New York City
10 Lincoln Center Plaza, New York City
298 First Avenue, New York City
183 Seventh Avenue, New York City

Below, we have written down the result of geocoding the "buggy" addresses manually using the google maps user interface:

In [15]:
#Maually corrected Geocodes
addressm.iloc[49]['Geocode'] = (40.800113, -73.940607)
addressm.iloc[52]['Geocode'] = (40.731681, -73.981837)
addressm.iloc[67]['Geocode'] = (40.799129, -73.941801)
addressm.iloc[69]['Geocode'] = (40.795961, -73.934174)
addressm.iloc[70]['Geocode'] = (40.795961, -73.934174)
addressm.iloc[97]['Geocode'] = (40.744852, -73.976229)
addressm.iloc[101]['Geocode'] = (40.724333, -73.992682)
addressm.iloc[117]['Geocode'] = (40.754906, -73.996792)
addressm.iloc[118]['Geocode'] = (40.754906, -73.996792)
addressm.iloc[162]['Geocode'] = (40.765892, -73.954634)
addressm.iloc[163]['Geocode'] = (40.765892, -73.954634)
addressm.iloc[226]['Geocode'] = (40.780839, -73.949743)
addressm.iloc[231]['Geocode'] = (40.774695, -73.986728)
addressm.iloc[240]['Geocode'] = (40.813993, -73.956925)
addressm.iloc[242]['Geocode'] = (40.819488, -73.944606)
addressm.iloc[260]['Geocode'] = (40.724082, -74.006416)
addressm.iloc[261]['Geocode'] = (40.724082, -74.006416)
addressm.iloc[262]['Geocode'] = (40.724262, -74.007545)
addressm.iloc[263]['Geocode'] = (40.724262, -74.007545)
addressm.iloc[265]['Geocode'] = (40.714231, -73.994227)
addressm.iloc[266]['Geocode'] = (40.714231, -73.994227)
addressm.iloc[312]['Geocode'] = (40.823554, -73.937335)
addressm.iloc[315]['Geocode'] = (40.772293, -73.984000)
addressm.iloc[342]['Geocode'] = (40.829248, -73.936084)
addressm.iloc[356]['Geocode'] = (40.830368, -73.939648)
addressm.iloc[430]['Geocode'] = (40.707767, -73.990772)
addressm.iloc[431]['Geocode'] = (40.707767, -73.990772)
addressm.iloc[432]['Geocode'] = (40.707767, -73.990772)
addressm.iloc[433]['Geocode'] = (40.707767, -73.990772)
addressm.iloc[468]['Geocode'] = (40.772838, -73.983241)
addressm.iloc[484]['Geocode'] = (40.733484, -73.980689)
addressm.iloc[489]['Geocode'] = (40.742792, -73.996511)

In [18]:
#Choosing a graph for Manhattan
G = ox.graph_from_place('Manhattan, New York City', network_type = 'walk', simplify = False)

Now we have to add annother column for the nodes of the geocodes within the graph.

In [40]:
#Adding a column with Nodes to df
addressnode = []
for i in addressm['Geocode']:
    addressnode.append(ox.get_nearest_node(G, i))  
addressm.insert(3, 'Node', addressnode, True)

In [42]:
#Save data frame
#addressm.to_pickle('addressm.pkl')

In [43]:
addressm.head(29)

,Address,Borough,Geocode,Node
0,"540 West 145th Street, New York City",Manhattan,"(40.8260052, -73.949854)",561035361
56,"145 & 147 Madison Ave, New York City",Manhattan,"(40.74619633333333, -73.983977)",3252586222
57,"165 Madison Avenue, New York City",Manhattan,"(40.746812750000004, -73.98327882871746)",42445903
58,"191 Madison Avenue, New York City",Manhattan,"(40.74802628571428, -73.98264385714285)",4960503208
59,"199 Madison Avenue, New York City",Manhattan,"(40.7482878, -73.9824103)",4960503208
60,"227 Madison Avenue, New York City",Manhattan,"(40.7598067, -73.9741741)",3977886242
88,"175 East 96th Street, New York City",Manhattan,"(40.785616, -73.9498645)",7325349531
91,"201 West 106th Street, New York City",Manhattan,"(40.8006923, -73.9659254)",4205830395
94,"1020 Third Avenue, New York City",Manhattan,"(40.812824, -73.923829)",7477281986
99,"209 West 96th Street, New York City",Manhattan,"(40.7946572, -73.97102558044648)",4205805396
100,"411 Grand Street, New York City",Manhattan,"(40.711920199999994, -73.95384408072891)",3630219671
101,"411 Grand Street, New York City",Manhattan,"(40.711920199999994, -73.95384408072891)",3630219671
102,"109 West Houston Street, New York City",Manhattan,"(40.72743495, -74.00073330000001)",5829880525
106,"163 West 97th Street, New York City",Manhattan,"(40.7945587, -73.9687567)",5669156315
107,"163 West 97th Street, New York City",Manhattan,"(40.7945587, -73.9687567)",5669156315
115,"90 Bennett Avenue, New York City",Manhattan,"(40.8531163, -73.9355226)",42445689
118,"4961 Broadway, New York City",Manhattan,"(40.8681188, -73.9204207)",5071822867
122,"111 West 71st Street, New York City",Manhattan,"(40.77706815, -73.97959553350846)",42437384
123,"111 West 71st Street, New York City",Manhattan,"(40.77706815, -73.97959553350846)",42437384
135,"437 Lenox Avenue, New York City",Manhattan,"(40.812104142857144, -73.94244528571429)",3099326124
136,"448 Lenox Avenue, New York City",Manhattan,"(40.8123399, -73.9417629)",4207724583
137,"55 Lenox Avenue, New York City",Manhattan,"(40.8000674, -73.951543713737)",3099326117
138,"175 Varick Street, New York City",Manhattan,"(40.7272907, -74.0057436)",42439345
139,"175 Varick Street, New York City",Manhattan,"(40.7272907, -74.0057436)",42439345
140,"160 Varick Street, New York City",Manhattan,"(40.7265969, -74.00541)",3252582132
141,"160 Varick Street, New York City",Manhattan,"(40.7265969, -74.00541)",3252582132
142,"431 Canal Street, New York City",Manhattan,"(40.7232317, -74.0069711)",4142105803
143,"431 Canal Street, New York City",Manhattan,"(40.7232317, -74.0069711)",4142105803
144,"304 Hudson Street, New York City",Manhattan,"(40.7264039, -74.0072925)",42436359

Finally, we have to calculate the shortest distance. Unfortunately, this task demands so much computing power that have not finished it yet.

In [ ]:
import itertools

In [ ]:
Nodes = addressm['Node']

In [ ]:
permutations_object = itertools.permutations(Nodes)

In [ ]:
permutation_list = list(permutations_object)

In [ ]:
print(permutation_list)

In [ ]:
#Calculating the shortest distance
distancel = []
counter1 = 0 
for i in addressm['Node']:
    counter1 += 1
    print(counter1)
    distance = []
    for j in addressm['Node']:
        distance.append(nx.shortest_path_length(G, i, j, weight = 'length'))
    distancel.append(distance)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438

In [ ]:
#Saving the result
with open('distancel', 'wb') as f:
    pickle.dump(distancel, f)

tuple